

services:
  postgres-database:
    image: postgres
    container_name: postgres_db_container
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-service:
    container_name: redis-server
    restart: always
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  redis-gui:
    container_name: redis-insight
    restart: always
    image: redis/redisinsight
    ports:
      - 5540:5540
    volumes:
      - redisinsight:/data

    ## in order to connect redis gui to the redis server 
    ## run `docker inspect container_id` to get the ip address of container and then use it to connect at http://127.0.0.1:5540 

  django-server:
    env_file:
      - .env
    container_name: django_app
    #* Use in production, uncomment and all set.
    # command: gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 8 --timeout 0 project.wsgi:application  
    #! Use in development, remove when moving to production and use.
    command: python manage.py runserver 0.0.0.0:8000 
    volumes:
      - .:/app # this is volumne mounting , it is copying the code of the current directory into the /app in django-server filesystem
    build:
      context: .
      args:
        - SECRET_KEY=${SECRET_KEY}
        - DEBUG_MODE=${DEBUG_MODE}
        - REDIS_HOST=${REDIS_HOST}
        - REDIS_PORT=${REDIS_PORT}
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_HOST=${DB_HOST}
        - DB_PORT=${DB_PORT}
    ports:
      - 8000:8000

    depends_on:
      - redis-service
      - postgres-database
    # depends_on:
    #   postgres-database:
    #     condition: service_healthy
volumes:
  db-data:
  redis_data:
  redisinsight:

secrets:
  db-password:
    file: db/password.txt
