

services:
  postgres-database:
    image: postgres
    container_name: postgres_db_container
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-service:
    restart: always
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  django-server:
    env_file:
      - .env
    container_name: django_app
    volumes:
      - .:/code
    build:
      context: .
      args:
        - SECRET_KEY=${SECRET_KEY}
        - REDIS_HOST=${REDIS_HOST}
        - REDIS_PORT=${REDIS_PORT}
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_HOST=${DB_HOST}
        - DB_PORT=${DB_PORT}
    ports:
      - 8000:8000

    depends_on:
      - redis-service
      - postgres-database
    # depends_on:
    #   postgres-database:
    #     condition: service_healthy
volumes:
  db-data:
  redis_data:

secrets:
  db-password:
    file: db/password.txt
